### ISSUE TITLE
Could you post info about the ESP8266 device we used today? 

### ISSUE THREAD

**Issue by schollii** [binnes/esp8266Workshop#1]
I would like to purchase one like we used in class at IoT613 today, but I forgot to write down the vendor/model info. Looks like there are many vendors that make boards based on the ESP 8266, but I think to simplify using the course material, it is better to use the hardware that you guys test with.

**Comment by binnes** [comment]
It was a NodeMCU board.  There are many different clones available, but when purchasing take note if the header pins are pre-soldered or if you need to solder pins to the board incase you're not able to solder pins.
