### ISSUE TITLE
ibm watson do not show that device is connected

### ISSUE THREAD

**Issue by Dubi09** [binnes/esp8266Workshop#14]
Hello, I am trying to make IoT app based on esp8266, node-red and IBM cloud. I follow your [guide](https://binnes.github.io/esp8266Workshop/part2/CERT1.html).  I only use different sensors.

I had to solve some problems. I had to change the order of configTime() and Wifi,begin(). In your order, it didn't work me.

Now I am at part 2: IoT Security. I configured the IBM cloud and uploaded the certificate to esp. The ESP prints "MQTT connected" and begins to send data, but IBM Watson says that the device is not connected, but in section, connection protocols appear new message (attachment). It worked without TLS. I do not know what I did wrong. I append serial output and my code. 
I'm not sure if I added the certificate to chrome correctly.

Pavel
```
Connected to Miroslav
IP address: 192.168.0.107
Setup done
Loaded CA cert
Loaded key
Loaded client cert

Waiting for time
Time sync'd
Sun Oct 18 00:57:38 2020

MQTT Connected
{"d":{"temp":24.14,"humidity":61.1,"water_level":18.326,"soil_humidity":0}}
{"d":{"temp":24.14,"humidity":60.95,"water_level":18.343,"soil_humidity":0}}
{"d":{"temp":24.15,"humidity":61.02,"water_level":17.918,"soil_humidity":0}}
...
```

![Snímek obrazovky 2020-10-18 012037](https://user-images.githubusercontent.com/44214410/96355279-2d14f900-10e0-11eb-98c6-e14253c48c7b.png)

[data_aquisition.ino.txt](https://github.com/binnes/esp8266Workshop/files/5396850/data_aquisition.ino.txt)

**Comment by StingyDubi** [comment]
I found that the mqtt.status() returns 1 (MQTT_CONNECT_BAD_PROTOCOL). I am not sure what I have to do.

**Comment by Dubi09** [comment]
I found where is the problem, but I don't know how to solve it. Chrome do no use my CA certificate. I tried to install firefox, and everything works like. I tried to add it via MMC and directly in chrome.

**Comment by binnes** [comment]
Depending in the OS you are using you may need to add your certificate to your OS root certificates, or to the browser.  

In Chrome browser settings there is a Privacy and Security section, where you should find the option to Manage Certificates.  You need to ensure your root CA certificate is added to the trusted root certificates.
