### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kyleg907** [binnes/esp8266Workshop#4]
https://github.com/binnes/esp8266Workshop/blob/master/en/part3/INTERVAL.md

The  `IoT Workshop Arduino Program` link is broken. Either the link is wrong, or the arduino sketch needs to move to an NL directory, or this is a work in progress you already know about.

Link that currently works: https://github.com/binnes/esp8266Workshop/blob/master/IoTWorkshop.ino/IoTWorkshop.ino.ino

Link as coded: https://github.com/binnes/esp8266Workshop/blob/master/en/IoTWorkshop.ino/IoTWorkshop.ino.ino

**Comment by binnes** [comment]
Thanks for reporting Fixed in commit 4462ae981210f4e9679114688783a647337a9471
