### ISSUE TITLE
Can you please show the complete json in text format instead of just screenshot?

### ISSUE THREAD

**Issue by VarunLashkari** [binnes/esp8266Workshop#5]
https://github.com/binnes/esp8266Workshop/blob/master/en/part3/NODERED.md#step-4---how-to-import-a-prebuilt-flow-from-github
is the link but i couldn't find any text to be pasted in import menu.

**Comment by binnes** [comment]
This is a reference here, there is nothing to import, just showing you how to import.  

You don't import anything until the next part of the lab.  There is a comment **_Not here in Step 4, but in several sections below, there will be a Get the Code link._** indicating that you don't do anything here.
